# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]]
modId="examplemod"
version="1.0.0.0"
displayName="Example Mod"
displayURL="minecraftforge.net"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
Lets you craft dirt into diamonds. This is a traditional mod that has existed for eons. It is ancient. The holy Notch created it. Jeb rainbowfied it. Dinnerbone made it upside down. Etc.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
    
[[mods]]
modId="flansmod"
version="1.0.0"
displayName="Flans Mod Ultimate"
displayURL="flansmod.com"
credits="JamioFlan for the original mod, TheWillyJ, DerpiLupine, PrototypeTheta, war-monger, GolddolphinSKB-Fexcraftian and demitto for Flans Mod Ultimate, Bomb787 for suffering/updating this to 1.15.2."
authors="Bomb787"
Description='''
Guns, planes and other vehicles in Minecraft.
'''

[[dependencies.flansmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.flansmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"